name: Marc Dispensa
favicon: null
layout_spectrum: 0.13638250273652375
typography_spectrum: 0.8620781260542572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.26428811461664736
  lightness: 0.2457224370446056
  saturation: 0.26512217335402966
  rhythmicContrast: 0.2075315024703741
purpose: []
